# максимальное значение рентабельности на площадке для маркетов с заданной моделью
models:
  MTCH_QLF:
    min: 102
    avr: 107.5
    max: 108
  # в видах спорта где данный рынок не является нулевой форой, иначе проверяем по количеству исходов
  MTCH_DNB:
    min: 102
    avr: 107.5
    max: 108
  MTCH_R:
    min: 102
    avr: 110
    max: 110.5
  MTCH_DC:
    min: 102
    avr: 107.5
    max: 110.5
  # MTCH_HB, MTCH_HBP, MTCH_TTLG, MTCH_TTLP: в видах спорта где данные рынки являются основными форами/тоталами, иначе проверяем по количеству исходов 
  MTCH_HB:
    min: 102
    avr: 107.5
    max: 110.5
  MTCH_HBP:
    min: 102
    avr: 107.5
    max: 110.5
  MTCH_TTLG:
    min: 102
    avr: 107.5
    max: 110.5
  MTCH_TTLP:
    min: 102
    avr: 107.5
    max: 110.5
  # также используем это значение для моделей динамического точного счета по иннингам и половинам: MTCH_CSW1DYN, MTCH_CSW2DYN, MTCH_CSW3DYN, MTCH_CSW4DYN, MTCH_CSW12DYN, MTCH_CSW34DYN
  MTCH_CSDYN:
    min: 102
    avr: 111
    max: 135

# максимальное значение рентабельности на площадке для маркетов с заданным количеством исходов
selections:
  2:
    min: 102
    avr: 110
    max: 110.5
  3:
    min: 102
    avr: 112
    max: 112.5
  4:
    min: 102
    avr: 113.5
    max: 114
  5:
    min: 102
    avr: 115
    max: 115.5
  6:
    min: 102
    avr: 116.5
    max: 117
  7:
    min: 102
    avr: 118
    max: 118.5
  9:
    min: 102
    avr: 121
    max: 121.5
  11:
    min: 102
    avr: 124
    max: 124.5
  13:
    min: 102
    avr: 127
    max: 127.5
  14:
    min: 102
    avr: 130
    max: 130.5
  17:
    min: 102
    avr: 130
    max: 130.5
  27:
    min: 102
    avr: 130
    max: 130.5
