# Включение механизма понижения количества маркетов
enabled: true

# Настройки режима понижения росписи, необходимого для понижения количества маркетов
autofillReduction:
  # Уровень росписи по умолчанию, до которого нужно понизить действующий, если для него не задан уровень в настройке reductionLevels
  defaultReductionLevel: Low
  # Карта понижений уровня росписи, в которой ключ - уровень, который нужно понизить, значение - уровень, до которого понизить
  # Названия уровней должны соотвествовать enum com.panbet.logic.events.calculation.eventfillers.EventFillerManager.AutofillDeepMode
  reductionLevels:
    Medium: Low
    High: Low
    Super: Low
    Super2: Low

# Настройки джобы по удалению неактивных маркетов без ставок 
removeNotActiveWithoutBetMarketsJob:
  # Включение джобы по удалению неактивных маркетов без ставок 
  enabled: true
  # Задержка перед удалением неактивных маркетов без ставок после запуска режима понижения росписи (в миллисекундах)
  delayMs: 60000

# Период времени от текущего момента, в течении которого должен начаться лайв, чтобы попасть под понижение маркетов (в минутах)
liveSuspendTimePeriodMin: 15

# Период времени от текущего момента, в течении которого должно завершится доматчевое событие, чтобы попасть под понижение маркетов (в минутах)
prematchSuspendTimePeriodMin: 60