products:
  GiBackoffice:
    managementUserRight: GiBackofficeProductRolesRightsEdit
    productUserRights:
      - GiBackofficeProductMonitoringSettingsEdit
      - GiBackofficeLogin
      - GiBackofficePuntersDetails
      - GiBackofficePuntersDetailsElementaryStatistics
      - GiBackofficePuntersProviderReconciliation
      - GiBackofficeProductMonitoring
      - GiBackofficeProductMonitoringSettingsView
      - GiBackofficeProductReleasesView
      - GiBackofficeProductReleasesEdit
      - GiBackofficeProductContentView
      - GiBackofficeProductContentEdit
      - GiBackofficeProductBackgroundView
      - GiBackofficeProductBackgroundEdit
      - GiBackofficeProductBannersView
      - GiBackofficeProductBannersEdit
      - GiBackofficeProductGameReferencesView
      - GiBackofficeProductGameReferencesEdit
      - GiBackofficeProductDictionaryView
      - GiBackofficeProductDictionaryEdit
      - GiBackofficeProductMaintenanceView
      - GiBackofficeProductMaintenanceEdit
      - GiBackofficeProductRestrictionView
      - GiBackofficeProductRestrictionEdit
      - GiBackofficeProductLocaleView
      - GiBackofficeProductLocaleEdit
      - GiBackofficeProductRolesRightsView
      - GiBackofficeProductRolesRightsEdit
      - GiBackofficeProductFreeSpinView
      - GiBackofficeProductFreeSpinEdit
      - GiBackofficeDictaoReportView
      - GiBackofficeBetRestrictionsProductsView
      - GiBackofficeBetRestrictionsProductsEdit
      - GiBackofficeBetRestrictionsCustomersView
      - GiBackofficeBetRestrictionsCustomersEdit
      - GiBackofficeProductDictionaryEditFull
      - GiBackofficeProductGameReferencesEditFull
      - GiBackofficeProductLimitsView
      - GiBackofficeProductLimitsEdit
      - GiBackofficeProductLimitsEditFull
      - GiBackofficeProductCommercialView
      - GiBackofficeProductCommercialEdit
      - GiBackofficeLimitsDirectoryProductsView
      - GiBackofficeLimitsDirectoryProductsEdit
      - GiBackofficeLimitsDirectoryCustomersView
      - GiBackofficeLimitsDirectoryCustomersEdit

  Totalizator:
    managementUserRight: TotoProductRolesRightsEdit
    productUserRights:
      - TotoPerspectiveDraw
      - TotoPerspectiveSettings
      - TotoPerspectiveTickets
      - TotoDrawCreation
      - TotoDrawSwap
      - TotoDrawChangeJackPot
      - TotoDrawChangeFinishTime
      - TotoDrawChangeComment
      - TotoDrawChangeStatisticsAvailable
      - TotoDrawChangeAllowTotoResultEvent
      - TotoDrawChangeStateManualActive
      - TotoDrawChangeStateManualSuspend
      - TotoDrawChangeStateManualFinish
      - TotoDrawChangeStateManualVoid
      - TotoDrawChangeStateManualCalculate
      - TotoDrawChangeStateManualRecalculate
      - TotoDrawLocalisationChange
      - TotoDrawMatchAddManual
      - TotoDrawMatchAddFromDB
      - TotoDrawMatchBindFromDB
      - TotoDrawMatchRemove
      - TotoDrawMatchSwap
      - TotoDrawMatchResultEnter
      - TotoDrawMatchVoid
      - TotoDrawMatchChangeStartTime
      - TotoDrawMatchChangeName
      - TotoDrawMatchChangeNameInActiveState
      - TotoDrawMatchChangeCategory
      - TotoDrawMatchChangeComment
      - TotoDrawMatchLocalisationChangeManual
      - TotoDrawMatchLocalisationSynchronization
      - TotoDrawCurrencyRatesSynchronization
      - TotoDrawCurrencyRatesChange
      - TotoDrawMinStakesChange
      - TotoDrawRefreshPool
      - TotoDrawAlertProcess
      - TotoTicketVoid
      - TotoSettingsCurrencyChange
      - TotoEventResultDicEdit
      - TotoDrawMatchChangeCoefficients
      - TotoGamblerDrawBonusLengthChange
      - TotoProductRolesRightsEdit